name: Update Algolia-Search index

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: [ "Build ⚙ and Deploy 🚀" ]
    branches: [ master ]
    types: [ completed ]

jobs:
  update-algolia-index:
    runs-on: ubuntu-latest
    steps:
      - name: Create algolia scraper config
        run: >
          echo <<CONFIG '{
            "index_name": "test",
            "sitemap_urls": ["https://psi-4ward.github.io/zigbee2mqtt.io/sitemap.xml"],
            "stop_urls": [],
            "selectors": {
              "lvl0": {
                "selector": ".sidebar-heading.active",
                "global": true,
                "default_value": "Documentation"
              },
              "lvl1": ".theme-default-content h1",
              "lvl2": ".theme-default-content h2",
              "lvl3": ".theme-default-content h3",
              "lvl4": ".theme-default-content h4",
              "lvl5": ".theme-default-content h5",
              "text": ".theme-default-content p, .theme-default-content li",
              "lang": {
                "selector": "/html/@lang",
                "type": "xpath",
                "global": true
              }
            },
            "custom_settings": {
              "attributesForFaceting": ["lang"]
            }
          }'
          CONFIG
          >> algolia.json
       - run: cat algolia.json
       - run: curl https://psi-4ward.github.io/zigbee2mqtt.io/build.txt
#      - name: Update algolia docsearch
#        uses: darrenjennings/algolia-docsearch-action@master
#        with:
#          algolia_application_id: 'XXXXX83LWT'
#          algolia_api_key: 'xxxxxxxxxxxxxxxxxxxx42935deb8d9d'
#          file: 'algolia.json'
